apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: echobot
  namespace: test-namespace
spec:
  interval: 1m0s
  url: https://github.com/Fondos182/infra/tree/main/clusters/demo
  ref:
    tag: v0.2.2
  ignore: |
    # exclude all
    /*
    # include deploy dir
    !/deployments
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: echobot
  namespace: test-namespace
spec:
  interval: 10m0s
  path: ./deployments
  prune: true
  sourceRef:
    kind: GitRepository
    name: echobot
  validation: client