apiVersion: v1
kind: Pod
metadata:
  name: app-test
  namespace: test-namespace
  labels:
    app: app-test
spec:
  containers:
    - name: message
      image: 'ghcr.io/sngular/gitops-echobot:v0.1.0'
      env:
        - name: CHARACTER
          value: log de prueba
      resources:
        requests:
          cpu: 10m
          memory: 30Mi
        limits:
          cpu: 10m
          memory: 30Mi
